version: '3'
services:
    cdk:
        build: .
        env_file:
            - .env
        volumes:
            - .:/target

    codebuild:
        build:
            context: .
            dockerfile: Dockerfile-codebuild
        env_file:
            - .env
        volumes:
            - .:/target
