FROM amazonlinux:2

RUN yum install -y curl unzip

WORKDIR /tmp/aws-cli
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf /tmp/aws-cli


RUN curl -sL https://rpm.nodesource.com/setup_14.x | bash && \
    yum install -y nodejs

WORKDIR /target

RUN npm i -g aws-cdk
