version: '3'
services:
    cdk:
        build: ./cdk
        env_file:
            - .env
        volumes:
            - ./cdk:/target

    web:
        build: ./web
        ports:
          - 80:80

    codebuild:
        build: ./codebuild
        env_file:
            - .env
        volumes:
            - .:/target
            - //var/run/docker.sock:/var/run/docker.sock
